SalasInmobiliaria/Models/LoginView.cs
using System.ComponentModel.DataAnnotations;

namespace SalasInmobiliaria.Models
{
    public class LoginView
    {
        [DataType(DataType.EmailAddress)]
        public string Usuario { get; set; }
        [DataType(DataType.Password)]
        public string Clave { get; set; }
    }
}

SalasInmobiliaria/Controllers/PagoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SalasInmobiliaria.Models;

namespace SalasInmobiliaria.Controllers
{
    public class PagoController : Controller
    {
        protected readonly IConfiguration configuration;
        private readonly RepositorioPago repositorio;
        private readonly RepositorioContrato repoContrato;

        public PagoController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorio = new RepositorioPago(configuration);
            repoContrato = new RepositorioContrato(configuration);
        }
        // GET: PagoController
        [Authorize]
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View(lista);
        }

        // GET: PagoController/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }


        }

        // GET: PagoController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: PagoController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(IFormCollection collection)
        {
            

            try
            {
                return View();
            }
            catch (Exception ex)
            {

                return View();
            }
        }

        // GET: PagoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PagoController/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PagoController/Delete/5
        [Authorize]
        public ActionResult Eliminar(int id)
        {

            var pago = repositorio.ObtenerPorId(id);
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(pago);
        }

        // POST: PagoController/Delete/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, Pago pago)
        {
            try
            {

                repositorio.Baja(pago);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(pago);
            }
        }
    }
}

SalasInmobiliaria/Views/Shared/_DataTable.cshtml
<script type="text/javascript" >
    $(document).ready(function () {
        $('#tabla').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.11.2/i18n/es_es.json"
            }
        });
       
    });
</script>

SalasInmobiliaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalasInmobiliaria</title>
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Boostrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SalasInmobiliaria.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/img/favicon5.png" type="image/x-icon" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css">
</head>
<body id="body" style="display: grid; grid-template-rows: auto 1fr auto">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
            @if (!User.Identity.IsAuthenticated)
            { 
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SalasInmobiliaria</a>
                
                <a class="justify-content-end" href="@Url.Link("login", null)"><i class="fa-solid fa-door-open"></i> Entrar</a>
            }
            else
            {
                 <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SalasInmobiliaria</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                    <div class="collapse navbar-collapse justify-content-center" id="navbarTogglerDemo02">
                        <ul class="navbar-nav ">
                            <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Inquilino" asp-action="Index">Inquilinos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Propietario" asp-action="Index">Propietarios</a>
                                </li>
                                <li class="nav-item" >
                                    <a class="nav-link " asp-area="" asp-controller="Inmueble" asp-action="Index">Inmuebles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Contrato" asp-action="Index">Contratos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Pago" asp-action="Index">Pagos</a>
                                </li>
                                @if (User.IsInRole("Administrador") || User.IsInRole("SuperAdministrador"))
					            {
                                    <li class="nav-item">
                                        <a class="nav-link " asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                    </li>
                                }
                        </ul>
                
                    </div>
                        
                    <div class="text-white">
                         <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           <i class="fa-regular fa-user "></i>
                          </a>
                          <ul class="dropdown-menu dropdown-menu-end " >
                              <li ><a class="dropdown-item" >Editar Perfil</a></li>
                              <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#CambiarContraseña">Cambiar Contraseña</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" asp-controller="Usuarios" asp-action="Logout">Cerrar Sesión <i class="fa-solid fa-arrow-right-from-bracket"></i></a></li>
                          </ul>
                    </div>   
            }

        </nav>
        @* ---------------------------------------------------------------MODAL CAMBIAR CONTRASEÑA---------------------------------------------------------*@


                    <div class="modal fade" id="CambiarContraseña" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Cambio de contraseña</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form asp-controller="Usuarios" asp-action="CambiarContraseña">
                                  <div class="mb-3">
                                    <label for="contraActual" class="form-label">Contraseña Actual</label>
                                    <input type="password" class="form-control" id="contraActual" name="contraActual">
                                  </div>
                                  <div class="mb-3">
                                    <label for="ContraNueva" class="form-label">Contraseña Nueva</label>
                                    <input type="password" class="form-control" id="ContraNueva" name="ContraNueva">
                                  </div>
                                  <div class="mb-3">
                                    <label for="ContraNuevaRepe" class="form-label">Confirmar Contraseña</label>
                                    <input type="password" class="form-control" id="ContraNuevaRepe" name="ContraNuevaRepe">
                                  </div>

                                  <button type="submit" class="btn btn-primary" >Cambiar Contraseña</button>
                                </form>
                            </div>
                        </div>
                        </div>
                    </div>

    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            
            <div class="">
			    @if (ViewBag.Id != null)    // --------------------------------------------------MODIFICAR MENSAJES DE ALERTA---------------------------//
			    {//alta exitosa
				    <div class="alert alert-success alert-dismissible fade show" role="alert">
					    <strong>¡Éxito!</strong> @ViewBag.Id
					    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
						    <span aria-hidden="true"><span class="lnr lnr-cross-circle"></span></span>
					    </button>
				    </div>
			    }
			    else if (ViewBag.Mensaje != null)
			    {//cartel general
				    <div class="alert alert-info alert-dismissible fade show" role="alert">
					    <strong>Información:</strong> @ViewBag.Mensaje
					    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
						    <span aria-hidden="true"><span class="lnr lnr-cross-circle"></span></span>
					    </button>
				    </div>
			    }
			    else if (ViewBag.Error != null)
			    {//alta exitosa
				    <div class="alert alert-danger alert-dismissible fade show" role="alert">
					    <strong>¡Error!</strong> @ViewBag.Error
					    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
						    <span aria-hidden="true"><span class="lnr lnr-cross-circle"></span></span>
					    </button>
				    </div>
			    }
			    else if (!String.IsNullOrWhiteSpace(ViewBag.Error))
			    {//ocurrió un error
				    <environment names="Development">
					    <div class="alert alert-danger alert-dismissible fade show" role="alert">
						    <strong>¡Error!</strong> Ocurrió: @ViewBag.Error
						    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							    <span aria-hidden="true"><span class="lnr lnr-cross-circle"></span></span>
						    </button>
						    <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false"><span class="lnr lnr-plus-circle"></span></a>
						    <div class="collapse multi-collapse" id="multiCollapseExample1">
							    @ViewBag.StackTrace
						    </div>
					    </div>
				    </environment>
			    }
            </div>
            
            @RenderBody()
        </main>
            <br />
            <br />
            <br />
    </div>

    <footer class="border-top footer text-muted">

        <div class="container">

            &copy; 2022 - SalasInmobiliaria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//momentjs.com/downloads/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.2/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.js"></script>
@*    <script src="//momentjs.com/downloads/moment.min.js"></script>*@


    
    <script>
       $(document).ready(function(){

            $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true,
            
            'language': 'es',

            });

       });


       $.fn.datepicker.dates['es'] = {
          days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
          daysShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
          daysMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"],
          months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
          monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
          today: "Hoy",
          clear: "Borrar",
          format: "dd/mm/yyyy",
          titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
          weekStart: 0
        };
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

SalasInmobiliaria/Views/Shared/_Login.cshtml
@model SalasInmobiliaria.Models.UsuarioView
@{
    ViewData["Title"] = "_Login";
}

<h1>Acceder</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login" asp-controller="Usuarios">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>