SalasInmobiliaria/Models/Contrato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalasInmobiliaria.Models
{
    public class Contrato
    {
        [Display(Name = "Código")]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Garante")]
        public string NombreGarante { get; set; }
        [Required]
        [Display(Name = "Telefono ")]
        public string TelefonoGarante { get; set; }
        [Required]
        [Display(Name = "Dni")]
        public string DniGarante { get; set; }
        [Display(Name = "Monto/Mes")]
        public string Monto { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Fecha inicio")]
        public DateTime FechaInicio { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Fecha fin")]
        public DateTime FechaFin { get; set; }
        [Required]

        [Display(Name = "Inquilino")]
        public int IdInquilino { get; set; }
        [ForeignKey(nameof(IdInquilino))]
        public Inquilino Inqui { get; set; }


        [Display(Name = "Inmueble")]
        public int IdInmueble { get; set; }
        [ForeignKey(nameof(IdInmueble))]
        public Inmueble Inmu { get; set; }

    }
}

SalasInmobiliaria/Controllers/ContratoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SalasInmobiliaria.Models;

namespace SalasInmobiliaria.Controllers
{
    public class ContratoController : Controller
    {
        protected readonly IConfiguration configuration;

        private readonly RepositorioContrato repositorio;
        private readonly RepositorioInquilino repoInquilino;
        private readonly RepositorioInmueble repoInmueble;
        private readonly RepositorioPago repoPago;

        public ContratoController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorio = new RepositorioContrato(configuration);
            repoInquilino = new RepositorioInquilino(configuration);
            repoInmueble = new RepositorioInmueble(configuration);
            repoPago = new RepositorioPago(configuration);
        }
        [Authorize]
        // GET: ContratoController
        public ActionResult Index()
        {

            var lista = repositorio.ObtenerTodos();

            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            ViewBag.Error = TempData["Error"];
            return View(lista);
        }

        [Authorize]
        public ActionResult DesdeHasta(string desde, string hasta)
        {
            var fechaDesde = Convert.ToDateTime(desde);
            var fechaHasta = Convert.ToDateTime(hasta); 
            var contratos = repositorio.ObtenerTodos();
            List<Contrato> res = new List<Contrato>();

            foreach (var item in contratos)
            {
                if(item.FechaInicio>= fechaDesde && item.FechaFin <= fechaHasta)
                {
                    res.Add(item);
                }
            }
            ViewBag.Id = "Contratos encontrados dentro del parametro de fecha ingresado.";
            return View("Index", res);
        }

        [Authorize]
        public ActionResult CancelarContrato(int id)
        {
            try
            {
                var c = repositorio.ObtenerPorId(id);
                DateTime hoy = DateTime.Today;
                c.FechaFin = hoy;
                repositorio.CancelarContrato(c);
                TempData["Mensaje"] = "Contrato cancelado con exito.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Inquilino = repoInquilino.ObtenerTodos();
                ViewBag.Inmueble = repoInmueble.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return RedirectToAction(nameof(Index));
            }
        }


        [Authorize]
        public ActionResult PorInquilino(int id)
        {
            var lista = repositorio.BuscarPorInquilino(id);
            ViewBag.Id = "Inquilino encontrado con exito.";
            //ViewBag.Inquilino = repoInquilino
            return View("Index", lista);
        }

        [Authorize]
        public ActionResult PorInmueble(int id)
        {
            var lista = repositorio.BuscarPorInmueble(id);
            ViewBag.Id = "Inmueble encontrado con exito.";
            //ViewBag.Inmueble = repoInmueble
            return View("Index", lista);
        }
        [Authorize]
        public ActionResult PagoPorContrato(int id)
        {
            var lista = repoPago.BuscarPorContrato(id);
            //ViewBag.Pagos = lista;
            return Json(lista);
            //return View("index",lista);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearPago(int id, IFormCollection collection)
        {
            Pago pago = new Pago();

            try
            {
                if (ModelState.IsValid)
                {
                    
                    pago.Importe = Int32.Parse(collection["Importe"]);
                    DateTime hoy = DateTime.Now;

                    //Console.WriteLine(hoy.ToShortDateString());

                    pago.Fecha = Convert.ToDateTime(hoy.ToShortDateString());

                    pago.IdContrato = id;

                    if (repoPago.BuscarPorContrato(id).Count==0)
                    {
                        pago.NPago = 1;
                    }
                    else
                    { 
                        var lista = repoPago.BuscarPorContrato(id);
                        var pag = lista.LastOrDefault();
                        pago.NPago = pag.NPago + 1;

                    }

                    repoPago.Alta(pago);
                    TempData["Id"] = "Pago realizado con exito";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    //ViewBag.Inquilino = repoContrato.ObtenerTodos();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return RedirectToAction(nameof(Index));
            }
        }
        [Authorize]
        // GET: ContratoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        [Authorize]
        // GET: ContratoController/Create
        public ActionResult Create()
        {
            ViewBag.Inquilino = repoInquilino.ObtenerTodos();
            ViewBag.Inmueble = repoInmueble.ObtenerTodos();
            return View();
        }

        // POST: ContratoController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            Contrato contrato = new Contrato();
            try
            {
                if (ModelState.IsValid)
                {

                    contrato.NombreGarante = collection["NombreGarante"];
                    contrato.TelefonoGarante = collection["TelefonoGarante"];
                    contrato.DniGarante = collection["DniGarante"];
                    contrato.FechaInicio = Convert.ToDateTime(collection["FechaInicio"].ToString());
                    contrato.FechaFin = Convert.ToDateTime(collection["FechaFin"].ToString());
                    contrato.IdInquilino = Int32.Parse(collection["IdInquilino"]);
                    contrato.IdInmueble = Int32.Parse(collection["IdInmueble"]);
                    
                    DateTime hoy = DateTime.Today;

                    var puede = true;
                    var contratosDelInmueble = repositorio.BuscarPorInmueble(contrato.IdInmueble);



                    foreach (var item in contratosDelInmueble)
                    {
                        if(contrato.FechaInicio <= item.FechaInicio && contrato.FechaFin >= item.FechaFin)
                        {
                            //no lo puede alquilar
                            puede = false;
                            break;
                        }
                        else if(contrato.FechaInicio <= item.FechaFin && contrato.FechaFin >= item.FechaFin)
                        {
                            //no puede alquilar
                            puede = false;
                            break;
                        }
                        else if(contrato.FechaInicio <= item.FechaInicio && contrato.FechaFin >= item.FechaInicio)
                        {
                            //no puede alquilar
                            puede = false;
                            break;
                        }
                        
                        else if(contrato.FechaInicio >= item.FechaInicio && contrato.FechaFin <= item.FechaFin)
                        {
                            //no puede alquilar
                            puede = false;
                            break;
                        }
                    }
                    if (puede)
                    {
                        if (contrato.FechaInicio <= contrato.FechaFin)
                        {
                            Inmueble ii = repoInmueble.ObtenerPorId(contrato.IdInmueble);
                            contrato.Monto = ii.Precio;
                            repositorio.Alta(contrato);
                            TempData["Id"] = "Contratos creado con exito";
                            return RedirectToAction(nameof(Index));
                        }
                        else
                        {
                            TempData["Error"] = "La fecha de fin de contrato no puede ser menor a la de inicio";
                            return RedirectToAction(nameof(Index));
                        }

                    }
                    else
                    {
                        TempData["Error"] = "No se puede alquilar el inmueble en esas fechas";
                        return RedirectToAction(nameof(Index));
                    }
                }
                else
                {
                    ViewBag.Inquilino = repoInquilino.ObtenerTodos();
                    ViewBag.Inmueble = repoInmueble.ObtenerTodos();
                    return View(contrato);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(contrato);
            }
        }
        [Authorize]
        // GET: ContratoController/Edit/5
        public ActionResult Editar(int id)
        {
            var contrato = repositorio.ObtenerPorId(id);
            ViewBag.Inquilino = repoInquilino.ObtenerTodos();
            ViewBag.Inmueble = repoInmueble.ObtenerTodos();
            if (TempData.ContainsKey("Mensaje"))

SalasInmobiliaria/Views/Contrato/Create.cshtml
@model SalasInmobiliaria.Models.Contrato

@{
    ViewData["Title"] = "Crear contrato";

}
<h1>Create</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreGarante" class="control-label">Nombre Garante</label>
                <input asp-for="NombreGarante" class="form-control" required/>
                <span asp-validation-for="NombreGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoGarante" class="control-label">Telefono Garante</label>
                <input asp-for="TelefonoGarante" class="form-control" required/>
                <span asp-validation-for="TelefonoGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DniGarante" class="control-label"> Dni Garante</label>
                <input asp-for="DniGarante" class="form-control" required/>
                <span asp-validation-for="DniGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label">Fecha inicio contrato</label>
                <div class=" justify-content-sm-center justify-content-start px-1"> <input asp-for="FechaInicio" type="text" id="dp1" class="datepicker" placeholder="Fecha Inicio" name="FechaInicio" readonly><span class="fa fa-calendar" required></span> </div>
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label">Fecha fin contrato</label>
                @*<input asp-for="FechaFin" class="form-control type="date"  />*@
                 <div class=" justify-content-sm-center justify-content-start px-1"> <input asp-for="FechaFin" type="text" id="dp1" class="datepicker" placeholder="Fecha Caduca" name="FechaFin" readonly><span class="fa fa-calendar" required></span> </div>
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label class="control-label">Inquilino</label>
                <select class="form-control" name="IdInquilino">
                    @foreach (var item in (IList<Inquilino>)ViewBag.Inquilino)
                    {
                        <option value="@item.Id">@(item.ToString())</option>
                    }
                </select>
                <span asp-validation-for="IdInquilino" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label class="control-label">Direccion inmueble</label>
                <select class="form-control" name="IdInmueble">
                    @foreach (var item in (IList<Inmueble>)ViewBag.Inmueble)
                    {
                        <option value="@item.Id">@(item.ToString())</option>
                    }
                </select>
                <span asp-validation-for="IdInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>

    <a asp-action="Index">Volver a la lista</a>
    <br />
    <br />
    <br />
    <br />

</div>

SalasInmobiliaria/Views/Contrato/Editar.cshtml
@model SalasInmobiliaria.Models.Contrato

@{
    ViewData["Title"] = "Editar";
    var Inmueble = (IList<Inmueble>)ViewBag.Inmueble;
    var Inquilino = (IList<Inquilino>)ViewBag.Inquilino;
}

<h1>Editar</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreGarante" class="control-label"></label>
                <input asp-for="NombreGarante" class="form-control" required/>
                <span asp-validation-for="NombreGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoGarante" class="control-label"></label>
                <input asp-for="TelefonoGarante" class="form-control" required/>
                <span asp-validation-for="TelefonoGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DniGarante" class="control-label"></label>
                <input asp-for="DniGarante" class="form-control" required/>
                <span asp-validation-for="DniGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" required/>
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label">Fecha inicio contrato</label>
                <div class=" justify-content-sm-center justify-content-start px-1"> <input asp-for="FechaInicio" asp-format="{0:dd/MM/yyyy}" type="text" id="dp1" class="datepicker" placeholder="Fecha Inicio" name="FechaInicio" readonly><span class="fa fa-calendar" required></span> </div>
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label">Fecha fin contrato</label>
                <div class=" justify-content-sm-center justify-content-start px-1"> <input asp-for="FechaFin" asp-format="{0:dd/MM/yyyy}" type="text" id="dp1" class="datepicker" placeholder="Fecha Caduca" name="FechaFin"  readonly><span class="fa fa-calendar" required></span> </div>
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>

    <a asp-action="Index">Volver a la lista</a>
    <br/>
    <br/>
    <br/>
    <br/>
</div>

SalasInmobiliaria/Views/Contrato/Eliminar.cshtml
@model SalasInmobiliaria.Models.Contrato

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contrato</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DniGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DniGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Monto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Monto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdInquilino)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdInquilino)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdInmueble)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdInmueble)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SalasInmobiliaria/Views/Contrato/Index.cshtml
@model IEnumerable<SalasInmobiliaria.Models.Contrato>

@{
    ViewData["Title"] = "Index";

    var Pagos = (IList<Pago>)ViewBag.Pagos;

}



<h1>Listado de Contratos</h1>

<p class="text-end">
    <a asp-action="Create"> Crear contrato</a>
</p>


<div>
    <form asp-action="DesdeHasta" method="get">
      <div class="mb-3">
        <label for="Desde">Desde:</label>
        <input name="desde" id="dp1" type="text" class="datepicker" placeholder="Desde" required><span class="fa fa-calendar"></span>
      </div>
      <div class="mb-3">
        <label for="Hasta"> Hasta :</label> 
        <input name="hasta" id="dp1" type="text" class="datepicker" placeholder="Hasta" required><span class="fa fa-calendar"></span>
      
        <button style="width:10%; height:30%" type="submit" class="btn btn-dark">Buscar</button>
        </div>
    </form>
    <br />
</div>
<table class="table" id="tabla">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreGarante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelefonoGarante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DniGarante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdInquilino)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdInmueble)
            </th>
            <th>
                Acciones
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreGarante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoGarante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DniGarante)
            </td>
            <td>
               $ @Html.DisplayFor(modelItem => item.Monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFin)
            </td>
            <td>
                @Html.ActionLink(item.Inqui.ToString(), "PorInquilino", new {  id=item.Inqui.Id  })
            </td>
            <td>
                @Html.ActionLink(item.Inmu.ToString(), "PorInmueble", new {  id=item.Inmu.Id  })
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.Id" title="Editar"><i class="fa-solid fa-pen"></i></a>&nbsp;
                <a asp-action="Eliminar" asp-route-id="@item.Id" title="Eliminar"><i class="fa-solid fa-trash-can"></i></a>&nbsp;
               @* <button title="Pagos" onclick="llenarTabla(@item.Id)"><i class="fa-solid fa-dollar-sign"></i></button>&nbsp;*@
                <a id="btnPagos" href="" data-bs-toggle="modal" data-bs-target="#ModalPagos" onclick="llenarTabla(@item.Id);"><i class="fa-solid fa-dollar-sign"></i></a>&nbsp;
                <a id="btnPagar" href="" data-bs-toggle="modal" data-bs-target="#ModalCrearPago@{@item.Id}" ><i class="fa-solid fa-cart-shopping"></i></a>&nbsp;
                <a href="" value="Cancelar" type="button" data-bs-toggle="modal" onclick='calcular("@item.Id","@item.FechaInicio","@item.FechaFin", "@item.Monto")'><i class="fa-solid fa-ban"></i></a>
                
                @*-----------------------------------------------------------Modal CREAR PAGO-----------------------------------------------------------*@

                <div class="modal fade" id="ModalCrearPago@{@item.Id}" tabindex="-1" aria-labelledby="crearModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="crearModalLabel">Crear Pago</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form asp-action="CrearPago" asp-controller="Contrato" asp-route-id="@item.Id" method="post">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    
                                    <div class="form-group">
                                        <label for="" class="control-label">Importe a pagar</label>

                                    </div>
                                    <div class="form-Importe">
                                        <label for="Importe" class="control-label">Cuota Mensual</label>
                                        <br>
                                        <input name="Importe" class="form-control" placeholder="$"/>
                                        <br>
                                        <span for="Importe" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="Pagar" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <!---------------------------------------------------------------- MODAL CANCELAR PAGOS ----------------------------------------------------------->


                <div class="modal fade" id="ModalCancelarContrato@{@item.Id}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body" >
                            <form asp-action="CancelarContrato" asp-controller="Contrato" asp-route-id=@item.Id method="post">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    
                                <div class="form-group" id="ModalBodyCancelar">
                                    <label for="" class="control-label">Cancelar alquiler</label>
    
                                    <div id="mensaje"></div>
                                    
                                </div>
                                    <div class="form-group">
                                        <input type="submit" value="Cancelar" class="btn btn-primary" />
                                    </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Close</button>
                        </div>
                    </div>
                    </div>
                </div>

            </td>
        </tr>
}
    </tbody>
</table>



@*-----------------------------------------------------------Modal PAGOS X CONTRATO-----------------------------------------------------------*@

<div class="modal fade" id="ModalPagos" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-xl modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel"> Pagos </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Codigo de Pago
                    </th>
                    <th>
                        Fecha de Pago
                    </th>
                    <th>
                        $ Monto
                    </th>
                    <th>
                        Numero de pago
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="ModalTablePagos">
        
            </tbody>
        </table>

      </div>
    </div>
  </div>
</div>


<script type="text/javascript" >

    function calcular(id, fechaInicio, fechaFin, monto){
        var idModal = "#ModalCancelarContrato" + id;
        

        var splitFechaInicio = fechaInicio.split(" ");
        var splitfechaFin = fechaFin.split(" ");

        var fecha1 = moment(splitFechaInicio);
        var fecha2 = moment(splitfechaFin);
        
        var now = moment();

        var difhoy = now.diff(fecha1, 'days');
        var dif = fecha2.diff(fecha1, 'days');

        var mitad = dif/2;

        var mensaje = document.getElementById("mensaje");

        @*mensaje.innerHTML = "";*@

        if (mitad > difhoy) {
            var total = monto * 2;
            alert("debera pagar como multa $" + total + " pesos por cancelar y permanecer menos de la mitad del tiempo");
            
            //mensaje.innerHTML  = "<p> debera pagar como multa $" + total + " pesos por cancelar y permanecer menos de la mitad del tiempo</p>";
            console.log("si");
            console.log(mensaje);
        } else {
            var total = monto;
            alert("debera pagar como multa $" + total + " pesos por cancelar y permanecer mas de la mitad del tiempo")
            //mensaje.innerHTML  = "<p>debera pagar como multa $" + total + " pesos por cancelar y permanecer mas de la mitad del tiempo </p>";
            console.log(mensaje);
            console.log("no");
            
        }

        $(idModal).modal('show');
        console.log(mitad);
        console.log(difhoy);
    }


</script>



<script>

    function llenarTabla(id){
        $.ajax({
            type:'GET',
            url:'@Url.Action("PagoPorContrato","Contrato")',
            data: {'id': id},
            success: function (data){
                $('#ModalTablePagos').html("")
                console.log(data)
                if(data.length != 0){
                    data.forEach(function(e)
                            {
                                var fecha = e.fecha.split("T")
                                console.log(fecha)
                                var mostrar = fecha[0].split("-")

                                $('#ModalTablePagos').append(`<tr>` + `<td> ${e.id} </td>` +  `<td> ${mostrar[2]}/${mostrar[1]}/${mostrar[0]} </td>` + `<td> $ ${e.importe} </td>` + `<td> ${e.nPago} </td>` + `</tr>`) 
      
                            })
                }
             }
        })
    }
    
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_DataTable");}

}